version: '2.3'

services:

  salgan_pytorch:
    image: salgan_pytorch
    container_name: salgan_pytorch
    working_dir: /home
    build: .
    ipc: host
    volumes:
      - ../src:/home/code
      - /media/eHD/juanjo/DATASETS/:/home/dataset
      - /media/eHD/juanjo/TRAIN_POOL/:/home/code/trained_models
      - /media/eHD/juanjo/SALIENCY_MAPS/:/home/saliency_maps
    environment:
      - PYTHONPATH=/home/code
    ports:
      - 6006:6006
    runtime: nvidia
