version: '2.3'

services:

  salgan_pytorch:
    image: salgan_pytorch
    container_name: salgan_pytorch
    working_dir: /home
    build: .
    user: ${CURRENT_UID}
    volumes:
      - ../src:/home/code
      - /home/enric/Downloads/juanjo/DATASETS/LEDOV:/home/dataset
      - /home/enric/Downloads/juanjo/TRAINED_MODELS/:/home/code/trained_models
      - /home/enric/Downloads/juanjo/SALIENCY_MAPS/:/home/saliency_maps
    environment:
      - PYTHONPATH=/home/code
    ports:
      - 6006:6006
      - 6007:6007
      - 8888:8888
    runtime: nvidia
